apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ingress-routing.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      {{- range $index, $item := .Values.ingress }}
      - backend:
          serviceName: {{ $item.serviceName }}
          servicePort: {{ $item.servicePort }}
        {{ if $item.path -}}
        path: {{ $item.path }}
        {{- end }}
      {{- end }}